update GHA to use Edgee CLI

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -46,8 +46,14 @@ jobs:
             - uses: actions-rust-lang/setup-rust-toolchain@v1
               with:
                   target: wasm32-wasip2 # WebAssembly target
-            - run: make build-no-edgee
-
+            - uses: edgee-cloud/install-edgee-cli@v0.1.0
+            - run: edgee component build
+            - name: Verify .wasm file exists
+              run: |
+                if [ ! -f "./kinesis.wasm" ]; then
+                    echo "❌ Error: kinesis.wasm not found" >&2
+                    exit 1
+                fi
     test:
         name: cargo test
         runs-on: ubuntu-latest
